com.thesoftwareguild_LawInOrder_war_1.0-SNAPSHOT_1/src/main/java/com/thesoftwareguild/lawinorder/dto/PostTemplate.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.thesoftwareguild.lawinorder.dto;

import java.time.LocalDate;

/**
 *
 * @author apprentice
 */
public interface PostTemplate {

    public void setPostId(int id);

    public int getPostId();

    public String getPostBody();

    public void setPostBody(String postBody);

    public void setPostTitle(String postTitle);

    public String getPostTitle();

    public void setPostType(PostType type);

    public PostType getPostType();

    public int getUserId();

    public void setUserId(int id);

    public boolean getIsPrivate();

    public void setIsPrivate(boolean priv);

    public LocalDate getPublishDate();

    public LocalDate getLastEditDate();

    public void setPublishDate(LocalDate date);

    public void setLastEditDate(LocalDate editDate);

    public void setPostExcerpt(String excerpt);

    public String getPostExcerpt();

    public void setPubStatus(PubStatus status);

    public PubStatus getPubStatus();

//    public void setTagsAsString(String tags);
//    
//    public String getTagsAsString();
//    
//    public String[] getTags();
//    
//    public void setTags(String[] tags);
    //    public String getAuthor();
//    
//    public void setAuthor(String author);
}

com.thesoftwareguild_LawInOrder_war_1.0-SNAPSHOT_1/src/main/java/com/thesoftwareguild/lawinorder/control/BlogDisplayController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.thesoftwareguild.lawinorder.control;

import com.thesoftwareguild.lawinorder.dao.LawInOrderDao;
import com.thesoftwareguild.lawinorder.dao.PostPublisher;
import com.thesoftwareguild.lawinorder.dto.PubStatus;
import com.thesoftwareguild.lawinorder.dto.Publication;
import com.thesoftwareguild.lawinorder.dto.Tag;
import com.thesoftwareguild.lawinorder.exception.ResourceNotFoundException;
import com.thesoftwareguild.lawinorder.dto.User;
import java.util.List;
import java.util.stream.Collectors;
import javax.inject.Inject;
import org.springframework.http.HttpStatus;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;

/**
 *
 * @author calarrick
 */
@Controller
@RequestMapping({"/"})
public class BlogDisplayController {

    private final LawInOrderDao dao;
    private final PostPublisher pub;

    //SET TO FALSE TO DISABLE RESET FROM FRONT END

    private boolean resetOn = true;


    @Inject
    public BlogDisplayController(LawInOrderDao dao, PostPublisher publisher) {
        this.dao = dao;
        this.pub = publisher;

        //temporary hard-coded user and role
        //using this on *first* run of project in your build
        //will provide these
        //shouldn't need anymore with ability to create user on front end
//    User user1 = new User();
//    Role role1 = new Role();
//    user1.setUsername("Author McAuthor");
//    user1.setEmail("author@author.com");
//    user1.setPassword("password");
//    role1.setRoleName("ROLE_ADMIN");
//    dao.addUser(user1);
//    dao.addRole(role1);
    }

    @RequestMapping(value = "/", method = RequestMethod.GET)
    public String mainSiteDisplay() {
        return "index";

    }

    @RequestMapping(value = "/posts", method = RequestMethod.GET)
    @ResponseBody
    public List<Publication> getPosts() {

        return dao.getAllPosts().stream().filter(p -> p.getPubStatus().equals(PubStatus.PUBLISH)).map(p -> pub.publicationBuilder(p))
                .collect(Collectors.toList());
//delivers all post-connected content. 
//may want streamlined methods where only want info
//from main post table
    }


    

    @RequestMapping(value = "/reset", method = RequestMethod.GET)
    public String cleanDB() {
        if (resetOn) {
            dao.cleanDB();
        }
        return "index";
    }

    @RequestMapping(value = "/post/{id}", method = RequestMethod.PUT)
    @ResponseStatus(HttpStatus.NO_CONTENT)
    public void putPost(@PathVariable("id") int id, @RequestBody Publication updateContent){
      
        pub.processNewPublication(id, updateContent);
        
    }
    
    @RequestMapping(value="/address/{id}", method=RequestMethod.DELETE)
    @ResponseStatus(HttpStatus.NO_CONTENT)
    public void deletePost(@PathVariable("id") int id){
        
        
        
                pub.removePostPageFromActive(id);
        
            }
    
    
    
    
    @RequestMapping(value = "/post/{id}", method = RequestMethod.GET)
    @ResponseBody
    public Publication getSinglePost(@PathVariable("id") int id) {
//        List<Post> r = new ArrayList<>();
//        r.add(dao.getPostById(id));
//        return r;
    
        try {
            return pub.publicationBuilder(dao.getPostById(id));
        } catch (NullPointerException e) {
            throw new ResourceNotFoundException();
        }
        //not sure if this is better solution versus two possible alternatives of 
        //setting the underlying program logic to return a "null" post or of 
        //allowing Tomcat to return the null pointer exc to go to the client 
        //(which has the advantage
        //of revealing a stack trace but seams less 'RESTful' and decoupled, esp
        //for a server-client interaction 'in the wild' 

        //so I'm inclined to think 404 probably is actually 'right' from client
        //contract perspective as most likely explanation of any bad query here
        //thoughts?
    }

    @RequestMapping(value = "/page/{id}", method = RequestMethod.GET)
    @ResponseBody
    public Publication getSinglePageAjax(@PathVariable("id") int id) {


        try {
            return pub.publicationBuilder(dao.getStaticPageByPostId(id));
        } catch (NullPointerException e) {
            throw new ResourceNotFoundException();
        }
        //as above. 404 is likely the most appropriate communication to the client of
        //the underlying cause of any failure of this method that would throw a null pointer
        //on the publicationBuilder method call


    }

    @RequestMapping(value = "/pages", method = RequestMethod.GET)
    @ResponseBody
    public List<Publication> getPages() {
        return dao.getAllStaticPages().stream().map(p -> pub.
                publicationBuilder(p))
                .collect(Collectors.toList());
        //definitely want to let Spring/Tomcat generate/handle exception in their default 
        //manner on these, as any failure would be indicative of very unexpected
        //bad behavior somewhere in the application (like a database server out of 
        //commission or something)
    }

    @RequestMapping(value = "/tag/{tag}", method = RequestMethod.GET)
    @ResponseBody
    public List<Publication> getPostsByTag(@PathVariable("tag") String tag) {

        Tag queryBy = dao.getTagByName(tag);

        return dao.getPostsByTag(queryBy.getTagId()).stream().map(p -> pub.
                publicationBuilder(p))
                .collect(Collectors.toList());
    }

    @RequestMapping(value = "/posts/author", method = RequestMethod.GET)
    @ResponseBody
    public List<Publication> getAuthorPosts() {

        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
        User user = dao.getUserByUsername(auth.getName()).get(0);
        int userId = user.getUserId();

        return dao.getDraftsByUserId(userId).stream().map(p -> pub.publicationBuilder(p))
                .collect(Collectors.toList());
    }

    @RequestMapping(value = "/posts/admin", method = RequestMethod.GET)
    @ResponseBody
    public List<Publication> getPostsPendingForAdmin() {

        return dao.getAllPosts().stream()
//                .filter(p -> p.getPubStatus().equals(PubStatus.DRAFT))
                .map(p -> pub.publicationBuilder(p))
                .collect(Collectors.toList());
    }

}

com.thesoftwareguild_LawInOrder_war_1.0-SNAPSHOT_1/src/main/java/com/thesoftwareguild/lawinorder/control/LoginController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.thesoftwareguild.lawinorder.control;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

/**
 *
 * @author apprentice
 */
@Controller
public class LoginController {
    
    @RequestMapping(value="/login", method=RequestMethod.GET)
    public String showLoginForm() {
        return "login";
    }
    
}

com.thesoftwareguild_LawInOrder_war_1.0-SNAPSHOT_1/src/main/java/com/thesoftwareguild/lawinorder/control/PostEditorController.java
package com.thesoftwareguild.lawinorder.control;

import com.thesoftwareguild.lawinorder.dao.LawInOrderDao;
import com.thesoftwareguild.lawinorder.dao.PostPublisher;
import com.thesoftwareguild.lawinorder.dto.Post;
import com.thesoftwareguild.lawinorder.dto.Publication;
import com.thesoftwareguild.lawinorder.dto.Tag;
import java.util.List;
import javax.inject.Inject;
import org.jsoup.Jsoup;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;

@Controller
@RequestMapping({"/"})
public class PostEditorController {

    private final LawInOrderDao dao;
    private final PostPublisher pub;

    @Inject
    public PostEditorController(LawInOrderDao dao, PostPublisher publisher) {
        this.dao = dao;
        this.pub = publisher;
    }

    
    //Returns admin page
    @RequestMapping(value = {"/control"}, method = RequestMethod.GET)
    public String adminHome(Model model) {

        return "control";
    }


    
    @RequestMapping(value = "/publish", method = RequestMethod.POST)
    @ResponseBody
    public Publication addPublication(@RequestBody Publication newContent) {

        
        newContent.setPostBody(Jsoup.parse(newContent.getPostBody()).toString());

        
        //postPublisher will take in the 'full' object from a new publication and
        //process to dtos matched up against relational tables, and 
        //have dao add them to the database
        //will also 'rebuild' new publication from those new components (w/ any 
        //regularization that brings)

        return pub.processNewPublication(newContent);//returns 'processed' version of publication
 

    }
    
    
    @RequestMapping(value= "/toptags", method=RequestMethod.GET)
    @ResponseBody public List<Tag> getTop5Tags(){
        List<Tag> toTruncate = dao.getSortedTags();
        int upperIndex = Math.min(5, toTruncate.size());
        return toTruncate.subList(0, upperIndex);
    }
//    
//    @RequestMapping(value="/toptags", method=RequestMethod.GET)
//    @ResponseBody public List<Tag> getTop5Tags(){
//        List<Tag> toTruncate = dao.getSortedTags();
//        int upperIndex = Math.min(5, toTruncate.size());
//        return toTruncate.subList(0, upperIndex)
//    }


    
    
}

com.thesoftwareguild_LawInOrder_war_1.0-SNAPSHOT_1/src/main/java/com/thesoftwareguild/lawinorder/control/SinglePostPageController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.thesoftwareguild.lawinorder.control;

import com.thesoftwareguild.lawinorder.dao.LawInOrderDao;
import com.thesoftwareguild.lawinorder.dao.PostPublisher;
import com.thesoftwareguild.lawinorder.dto.PubStatus;
import com.thesoftwareguild.lawinorder.dto.Publication;
import com.thesoftwareguild.lawinorder.exception.ResourceNotFoundException;
import javax.inject.Inject;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.springframework.web.servlet.ModelAndView;

/**
 *
 * @author calarrick
 */
@Controller
@RequestMapping({"/"})
public class SinglePostPageController {

    private final LawInOrderDao dao;
    private final PostPublisher pub;

    @Inject
    public SinglePostPageController(LawInOrderDao dao, PostPublisher publisher) {
        this.dao = dao;
        this.pub = publisher;
    }

    @RequestMapping(value = "/{postUrl}", method = RequestMethod.GET)
    public ModelAndView viewSingle(@PathVariable("postUrl") String postUrl)
//            throws ResourceNotFoundException {
    {

        Publication post;
        
//            if (post.getPubStatus().equals(PubStatus.PUBLISH)) {
post = pub.publicationBuilder(dao.getStaticPageByUrl(postUrl));
            return new ModelAndView("single", "post", post);}
        
//        
//
//        try {
//            post = pub.publicationBuilder(dao.getStaticPageByUrl(postUrl));
//
//        } catch (NullPointerException e) {
//
//            try {
//                post = pub.publicationBuilder(dao.getPostByUrl(postUrl));
//
//            } catch (NullPointerException ex) {
//
//                throw new ResourceNotFoundException(postUrl);
//
//            }
//
//        }
//
//        if (post.getPubStatus().equals(PubStatus.PUBLISH)) {
//
//            return new ModelAndView("single", "post", post);
//        } else {
//            throw new ResourceNotFoundException(postUrl);
//        }

    

    @ExceptionHandler(ResourceNotFoundException.class)
    @ResponseStatus(HttpStatus.NOT_FOUND)
    public ModelAndView handleResourceNotFoundException(
            ResourceNotFoundException ex) {

        String message = ex.getMessage();

        return new ModelAndView("resourcenotfound", "message", ex);

    }

}

com.thesoftwareguild_LawInOrder_war_1.0-SNAPSHOT_1/src/main/webapp/jsp/Home.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="s" uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@ page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <title>Law in Order</title>
        <link href="css/bootstrap.css" rel="stylesheet">
        <link href='https://fonts.googleapis.com/css?family=Merriweather:400,400italic,700|Open+Sans:600|Open+Sans+Condensed:300,700' rel='stylesheet' type='text/css'>
        <link href="css/pagestyle.css" rel="stylesheet">

        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body data-base-url="${pageContext.request.contextPath}/">
        <div class="container">
            <div id ="header-div" class="row">
                <header>
                    <div id="title" class="col-xs-12">
                        <h1><a href=${pageContext.request.contextPath}>Law in Order</a></h1>
                    </div>
                    <div id="subtitle" class="col-xs-12">
                        <p>Putting the order in law since 2015</p>
                    </div>
                </header>
            </div>
            <nav id="nav-row" class="big-icon hidden-sm hidden-md hidden-lg hidden-xl col-xs-12">

                <div id="top-arrow" class="top-item"><a href="" class="" id="top-link">
                        <span class="menu-icon big-icon glyphicon glyphicon-triangle-top custom-icon"></span>
                    </a></div>

                <div id="toggler" class="top-item"><a href="" id="toggle-sidebar">
                        <span class="menu-icon big-icon glyphicon glyphicon-menu-hamburger custom-icon"></span>
                    </a></div>

            </nav>

            <div id="display-searched-tag"></div>

            <div class="row">
                <section id="post-area" class="col-xs-12 col-sm-8 col-md-9">
                    <ul id="post-list" class="post-list"></ul>

                </section>    

                <section id="sidebar" class="sidebar-default hidden-xs col-sm-4 col-md-3">
                    <h4>Most Popular Tags</h4>
                    <ul class="top-tags"></ul>
                    <h4>My Pages</h4>
                    <ul class="static-pages"></ul>
                    <h4>Quick Access</h4>
                    <ul>
                        <li><a href="${pageContext.request.contextPath}/admin">Admin Panel</a></li> 
                        <li><a href="${pageContext.request.contextPath}/">Go to Home Page</a></li>
                        <li><a href="#">About the Author</a></li>
                        <li><a href="#">Archives</a></li>

                    </ul>
                </section>
                <section id="big-sidebar" class="sidebar-default big-sidebar-hidden hidden-sm hidden-md hidden-lg hidden-xl">
                    <h4>Most Popular Tags</h4>
                    <ul class="top-tags"></ul>
                    <h4>My Pages</h4>
                    <ul class="static-pages"></ul>
                    <h4>Quick Access</h4>
                    <ul>
                        <li><a href="${pageContext.request.contextPath}/login">Log In</a></li> 
                        <li><a href="${pageContext.request.contextPath}/admin">Admin Panel</a></li> 
                        <li><a href="${pageContext.request.contextPath}/">Go to Home Page</a></li>
                        <li><a href="#">About the Author</a></li>
                        <li><a href="#">Archives</a></li>

                    </ul>
                </section>
            </div>


            <div class="row">
                <footer>
                    <div id="copyright">
                        <p>&copy; 2015 Lorem Ipsum</p>
                    </div>
                </footer>
            </div>
        </div>


        <!-- Scripts; ordering is important-->
        <script src="js/jquery-1.11.3.min.js"></script>
        <script src="js/bootstrap.min.js"></script>
        <script src="js/index.js"></script>
        <script src="js/layout.js"></script>
    </body>
</html>

com.thesoftwareguild_LawInOrder_war_1.0-SNAPSHOT_1/src/main/webapp/jsp/index.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="s" uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@ taglib prefix="sec" uri="http://www.springframework.org/security/tags" %>
<%@ page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <title>Law in Order</title>
        <link href="css/bootstrap.min.css" rel="stylesheet">
        <link href='https://fonts.googleapis.com/css?family=Merriweather:400,400italic,700|Open+Sans:600|Open+Sans+Condensed:300,700' rel='stylesheet' type='text/css'>
        <link href="css/pagestyle.css" rel="stylesheet">

        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body data-base-url="${pageContext.request.contextPath}/">
        <div class="container">
            <div id ="header-div" class="row">
                <header>
                    <div id="title" class="col-xs-12">
                        <h1 id="page-title"><a href=${pageContext.request.contextPath}>Law in Order</a></h1>
                    </div>
                    <div id="subtitle" class="col-xs-12">
                        <p>Putting the order in law since 2015</p>
                    </div>
                </header>
            </div>
            <nav id="nav-row" class="big-icon hidden-sm hidden-md hidden-lg hidden-xl col-xs-12">

                    <div id="top-arrow" class="top-item"><a href="" class="" id="top-link">
                            <span class="menu-icon big-icon glyphicon glyphicon-triangle-top custom-icon"></span>
                        </a></div>
                  
                    <div id="toggler" class="top-item"><a href="" id="toggle-sidebar">
                            <span class="menu-icon big-icon glyphicon glyphicon-menu-hamburger custom-icon"></span>
                        </a></div>
                   
                </nav>

            <div id="display-searched-tag"></div>

            <div class="row">
                <section id="post-area" class="col-xs-12 col-sm-8 col-md-9">
                    <ul id="post-list" class="post-list"></ul>

                </section>    

                <section id="sidebar" class="sidebar-default hidden-xs col-sm-4 col-md-3">
                    <h4>Most Popular Tags</h4>
                    <ul class="top-tags"></ul>
                    <h4>My Pages</h4>
                    <ul class="static-pages"></ul>
                    <h4>Quick Access</h4>
                    <ul>
                        <li><a href="${pageContext.request.contextPath}/login">Log In</a></li> 
                        <li><a href="${pageContext.request.contextPath}/control">Control Panel</a></li>
                        <li><a href="${pageContext.request.contextPath}/">Go to Home Page</a></li>
                        <li><a href="#">About the Author</a></li>
                        <li><a href="#">Archives</a></li>

                    </ul>
                </section>
                <section id="big-sidebar" class="sidebar-default big-sidebar-hidden hidden-sm hidden-md hidden-lg hidden-xl">
                    <h4>Most Popular Tags</h4>  
                    <ul class="top-tags"></ul>
                    <h4>My Pages</h4>
                    <ul class="static-pages"></ul>
                    <h4>Quick Access</h4>
                    <ul>
                        <li><a href="${pageContext.request.contextPath}/login">Log In</a></li> 
                        <li><a href="${pageContext.request.contextPath}/control">Control Panel</a></li> 
                        <li><a href="${pageContext.request.contextPath}/">Go to Home Page</a></li>
                        <li><a href="#">About the Author</a></li>
                        <li><a href="#">Archives</a></li>

                    </ul>
                </section>
            </div>
                        
                        
            <div class="row">
                <footer>
                    <div id="copyright">
                        <p>&copy; 2015 Lorem Ipsum</p>
                    </div>
                </footer>
            </div>
        </div>


        <!-- Scripts; ordering is important-->
        <script src="js/jquery-1.11.3.min.js"></script>
        <script src="js/bootstrap.min.js"></script>
        <script src="js/index.js"></script>
        <script src="js/layout.js"></script>
    </body>
</html>

com.thesoftwareguild_LawInOrder_war_1.0-SNAPSHOT_1/src/main/webapp/jsp/single.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="s" uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@ taglib uri="/WEB-INF/custom.tld" prefix="custom" %>
<%@ page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <title>${post.postTitle}: Law in Order</title>
        <link href="css/bootstrap.min.css" rel="stylesheet">
        <link href='https://fonts.googleapis.com/css?family=Merriweather:400,400italic,700|Open+Sans:600|Open+Sans+Condensed:300,700' rel='stylesheet' type='text/css'>
        <link href="css/pagestyle.css" rel="stylesheet">

        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body data-base-url="${pageContext.request.contextPath}/">
        
            <div class="container">
            <div id ="header-div" class="row">
                <header>
                    <div id="title" class="col-xs-12">
                        <h2 id="page-title"><a href=${pageContext.request.contextPath}>Law in Order</a></h1>
                    </div>
                    <div id="subtitle" class="col-xs-12">
                        <p>Putting the order in law since 2015</p>
                    </div>
                </header>
            </div>
            
                <nav id="nav-row" class="big-icon hidden-sm hidden-md hidden-lg hidden-xl col-xs-12">

                    <div id="top-arrow" class="top-item"><a href="" class="" id="top-link">
                            <span class="menu-icon big-icon glyphicon glyphicon-triangle-top custom-icon"></span>
                        </a></div>
                  
                    <div id="toggler" class="top-item"><a href="" id="toggle-sidebar">
                            <span class="menu-icon big-icon glyphicon glyphicon-menu-hamburger custom-icon"></span>
                        </a></div>
                   
                </nav>

            <div id="display-searched-tag"></div>

            <div class="row">
                <section id="post-area" class="col-xs-12 col-sm-9">


                    <div id="post-list" class="post-list">
                        <div class="single-post post">
                            <h1 class="post-title">
                                ${post.postTitle}
                            </h1>
                            <h3 class="post-byline"><span class="byline-author">${post.author}</span>, 
                                <span class="byline-date"><custom:formatDate pattern="MMMM d, uuuu" value="${post.publishDate}"/></span>

                            </h3>
                            <div class="post-body"> ${post.postBody}
                            </div>
                            <ul class="tag-area tag-list" id=${post.postId}-tags>             
                                <c:forEach  items="${post.tags}" var="currentTag">

                                    <li>
                                        <a href="#" class="tag" data-tag-name=${currentTag}>
                                            #${currentTag}</a>
                                    </li>


                                </c:forEach>          
                            </ul>

                        </div>
                    </div>

                </section>    

                <section id="sidebar" class="sidebar-default hidden-xs col-sm-3">
                    <h4>Most Popular Tags</h4>
                    <ul class="top-tags"></ul>
                    <h4>My Pages</h4>
                    <ul class="static-pages"></ul>
                    <h4>Quick Access</h4>
                    <ul>
                        <li><a href="${pageContext.request.contextPath}/admin">Admin Panel</a></li> 
                        <li><a href="${pageContext.request.contextPath}/">Go to Home Page</a></li>
                        <li><a href="#">About the Author</a></li>
                        <li><a href="#">Archives</a></li>

                    </ul>
                </section>
                        
                <section id="big-sidebar" class="sidebar-default big-sidebar-hidden hidden-sm hidden-md hidden-lg hidden-xl">
                    <h4>Most Popular Tags</h4>
                    <ul class="top-tags"></ul>
                    <h4>My Pages</h4>
                    <ul class="static-pages"></ul>
                    <h4>Quick Access</h4>
                    <ul>
                        <li><a href="${pageContext.request.contextPath}/control">Control Panel</a></li> 
                        <li><a href="${pageContext.request.contextPath}/">Go to Home Page</a></li>
                        <li><a href="#">About the Author</a></li>
                        <li><a href="#">Archives</a></li>

                    </ul>
                </section>
                <section id="big-sidebar" class="sidebar-default big-sidebar-hidden hidden-sm hidden-md hidden-lg hidden-xl">
                    <h4>Most Popular Tags</h4>
                    <ul class="top-tags"></ul>
                    <h4>Quick Access</h4>
                    <ul>
                        <li><a href="${pageContext.request.contextPath}/control">Control Panel</a></li> 
                        <li><a href="${pageContext.request.contextPath}/">Go to Home Page</a></li>
                        <li><a href="#">About the Author</a></li>
                        <li><a href="#">Archives</a></li>

                    </ul>
                </section>
            </div>
            <div class="row">
                <footer>
                    <div id="copyright">
                        <p>&copy; 2015 Lorem Ipsum</p>
                    </div>
                </footer>
            </div>
        </div>


        <!-- Scripts; ordering is important-->
        <script src="js/jquery-1.11.3.min.js"></script>
        <script src="js/bootstrap.min.js"></script>
        <script src="js/index.js"></script>
        <script src="js/layout.js"></script>
    </body>
</html>